### ISSUE TITLE
Errors when generating Krill API client library in Rust from OpenAPI spec

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#257]
Generating a Krill API client in Python 3 with the Krill 0.6.2 OpenAPI specification works as per the [instructions in the documentation](https://rpki.readthedocs.io/en/latest/krill/api.html#generating-client-code). However, when changing the generator language to rust instead of Python the generated library fails to build with stable rust 1.43.1. `cargo build` in the generated Cargo project directory causes the following errors:

```
$ cargo build
...
   Compiling krillapi v1.0.0 (/tmp/genrust/out)
error[E0412]: cannot find type `OneOfobjectobjectobjectobjectobject` in module `crate::models`
  --> src/models/inline_response_200_3_resources_classes.rs:21:37
   |
21 |     pub keys: Option<crate::models::OneOfobjectobjectobjectobjectobject>,
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `crate::models`

error[E0412]: cannot find type `OneOfobjectobject` in module `crate::models`
  --> src/models/inline_response_200_5.rs:17:40
   |
17 |     pub contact: Option<crate::models::OneOfobjectobject>,
   |                                        ^^^^^^^^^^^^^^^^^ not found in `crate::models`
...
error[E0282]: type annotations needed
  --> src/models/inline_response_200_3_resources_classes.rs:31:19
   |
31 |             keys: None,
   |                   ^^^^ cannot infer type for type parameter `T` declared on the enum `Option`

error[E0282]: type annotations needed
  --> src/models/inline_response_200_5.rs:23:22
   |
23 |             contact: None,
   |                      ^^^^ cannot infer type for type parameter `T` declared on the enum `Option`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0282, E0412.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `krillapi`.

To learn more, run the command again with --verbose.

```

**Comment by ximon18** [comment]
Perhaps interesting to note is that in my quick test using the [official Docker OpenAPI spec](https://docs.docker.com/engine/api/v1.40/) also generates a rust client library that doesn't compile.

**Comment by ximon18** [comment]
Closing as the OpenAPI spec document was [removed](https://github.com/NLnetLabs/krill/commit/ff85ea5170c92c759068fc2df02d3bd9c2e1fb36) from Krill in the 0.9.0 release.
